volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: ctoia/foodgram_backend
    env_file: .env
    volumes:
      - static:/app/static/
      - media:/app/media/
    depends_on:
      - db
  frontend:
    env_file: .env
    image: ctoia/foodgram_frontend
    volumes:
        - ./frontend/:/app/result_build/
  gateway:
    image: ctoia/foodgram_gateway
    volumes:
      - ./infra/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static:/static
      - media:/media
    ports:
      - 5000:80
    depends_on:
      - backend
      - frontend